# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48517ffa3f4fb6d3c1a95db6a3f7b0e499863b9892618ed40e8ac7599a1fb697876349deac8e738e52fdb5a7b77188dadba210c6c0c6fa1a532795def68038ea
  fd_key: 7V3IjgluJ9RDSMsq5j9XdscvfZiuj9Uetsnz5PNa
  fd_secret: PTWLvxDGjHc66qv28VC4ak6HJ18odOwuejjc0a2V
  domain_name: http://localhost:3000
  fd_domain: https://discothecorgi.frontdeskhq.com
  token:

test:
  secret_key_base: b8aa788b012bba8b676fb7d903137306e7f561e589eb7f00642117e8303884971af7f48e37155f1d44650d8a876a82e2ca542c104e288c536ad9fc900f5abf74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fd_key: 7V3IjgluJ9RDSMsq5j9XdscvfZiuj9Uetsnz5PNa
  fd_secret: PTWLvxDGjHc66qv28VC4ak6HJ18odOwuejjc0a2V
  domain_name: http://fdschedule.herokuapp.com
  fd_domain: https://discothecorgi.frontdeskhq.com
